// <auto-generated/>

[assembly: AssemblyProductAttribute("AppFunc")]
[assembly: AssemblyVersionAttribute("0.2.1")]
[assembly: AssemblyFileVersionAttribute("0.2.1.0")]
[assembly: ComVisibleAttribute(false)]

internal static class AssemblyVersionInformation {
    internal const string Version = "0.2.1";
}