// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyProductAttribute("AppFunc")]
[assembly: AssemblyVersionAttribute("0.2.1")]
[assembly: AssemblyFileVersionAttribute("0.2.1.0")]
[assembly: ComVisibleAttribute(false)]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.2.1";
    }
}
